apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: default
spec:
  secretName: wildcard-devops-taipei
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.devops.taipei"
  dnsNames:
  - "*.devops.taipei"
  - "devops.taipei"
  privateKey:
    algorithm: RSA
    size: 2048
