apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-cert
  namespace: lens-metrics
spec:
  secretName: prometheus-tls-secret
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "prometheus.devops.taipei"
