apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guestbook-tls-cert
  namespace: test
spec:
  secretName: guestbook-tls-secret
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.devops.taipei"
