name: 🐝 Manually deploy runners

on:
  workflow_call:
    inputs:
      TARGET_BRANCH:
        description: "The target branch"
        default: ""
        type: string
  workflow_dispatch: # deploy on demand
    inputs:
      target_scale_set:  # name our runner set
        # In this repository, this corresponds to the helm chart name in `/deployments/helm-***.yml`.
        # e.g., `ubi8` would target `/deployments/helm-ubi8.yml`
        description: "Which scale set to deploy?"
        default: "guestbook"
        type: choice
        required: true
        options:  # change these to your own names or change :point_up: to a `string` for freeform entry.
        - "guestbook"
        - "grafana"
        - "argo-cd" 
        - "kube-prometheus" 
      environment_name:  # this corresponds to the environments we set up for our `kubeconfig` files
        description: "Which environment to deploy to?"
        type: choice  # drop-down menus are fantastic!
        required: true
        options:  # change these to your own names or change :point_up: to a `string` for freeform entry.
        - "ghcr"
        - "awsecr"
        - "production" 
        default: "ghcr"
      runner_namespace:
        description: "Which namespace to deploy to?"
        type: choice
        required: true
        options:  # again, change this to your own namespaces
        - "runners"
        - "test"
        default: "test-runners"

jobs:
  Deploy:
    runs-on: [self-hosted, Linux, X64] # use the GitHub hosted runners to deploy the self-hosted runners in GHEC
    # If using GHES or GHAE, use another deployment, such as having CentOS redeploy Ubuntu and vice versa
    environment: ${{ github.event.inputs.environment_name }}

    steps:
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
    - name: Publish chart
      env:
        HELM_EXPERIMENTAL_OCI: '1'
        CHARTS_REPO: ghcr.io/devops-teamespace
        VERSION: ${{ github.ref_name }}
      run: |
        helm install "${{ github.event.inputs.target_scale_set }}" \
        --namespace "${{ github.event.inputs.runner_namespace }}" \
        oci://ghcr.io/devops-teamspace
