name: Push various oci helm-charts
on:
  workflow_dispatch:
    inputs:
      BUILD_ENV:
        description: 'The target build environment'
        required: true
        type: choice
        default: ghcr
        options:
          - ghcr
          - awsecr
          - gcp
  workflow_call:
    inputs:
      TARGET_BRANCH:
        description: "The target branch"
        default: ""
        type: string

jobs:
  Package-HelmCharts-for_GHRC:
    if: github.event.inputs.BUILD_ENV == 'ghcr'
    name: Package for GHRC
    environment: ${{ github.event.inputs.BUILD_ENV }}
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.TARGET_BRANCH || '' }}
        ssh-key: ${{ secrets.ECS_SSH_PRIVATE_KEY }}
    - name: Push Helm chart to OCI compatible registry (Github)
      uses: bsord/helm-push@v4.2.0
      with:
        useOCIRegistry: true
        registry-url:  oci://ghcr.io/devops-teamspace
        username: ${{ secrets.USERNAME }}
        access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        force: true
        chart-folder: charts/guestbook
