name: Release

on:
  release:
    types: 
    - created

jobs:
  publish-charts:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.10.0'
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
    
    - name: Publish chart
      env:
        HELM_EXPERIMENTAL_OCI: '1'
        CHARTS_REPO: ghcr.io/devops-teamespace
        VERSION: ${{ github.ref_name }}
      run: |
        CHART_VERSION=$(echo $VERSION | cut -c 2-)
        cd charts/guestbook
        helm dep up
        helm package . --version ${CHART_VERSION} --app-version ${VERSION}
        helm push guestbook-${CHART_VERSION}.tgz oci://${CHARTS_REPO}
